name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to the main branch
  schedule:
    - cron: '0 * * * *'  # Runs every hour (at the start of the hour)

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Increase the timeout to 10 minutes

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Ensure latest checkout action

    - name: Set up Python
      uses: actions/setup-python@v5  # Latest Python action
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install pandas Pillow gspread oauth2client

    - name: Run Python script
      run: |
        python scripts/main_script.py  # Executes the main script that generates the HTML file

    - name: Disable Jekyll
      run: |
        touch docs/.nojekyll  # Prevent Jekyll from processing your site

    - name: List files in docs directory  # Verifies the HTML file was generated
      run: |
        ls -l docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Updated to v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
        publish_dir: ./docs  # This is the directory where the HTML is generated
        publish_branch: gh-pages
        keep_files: true  # Preserve existing files in gh-pages branch
