name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install pandas Pillow

    - name: Run Python script
      run: |
        python scripts/main_script.py  # Executes the main script that generates the HTML file

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions
        publish_dir: ./docs  # This is the directory where the HTML is generated

    - name: Post to GitHub Pages
      run: echo "HTML deployed to GitHub Pages!"
