name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pandas Pillow gspread oauth2client

    - name: Create service account JSON file
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service_account.json  # Directly writes the JSON to a file

    - name: Run Python script
      run: |
        python scripts/main_script.py  # Run the script that accesses Google Sheets

    - name: Disable Jekyll
      run: |
        touch docs/.nojekyll  # Prevent Jekyll from processing your site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        publish_branch: gh-pages
        keep_files: true
